sudo: required
language: java
notifications:
  irc:
    on_success: never
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    channels:
    - chat.freenode.net#strimzi
    use_notice: true
jdk:
- oraclejdk8
services:
- docker
#addons:
#  apt:
#    packages:
#      - asciidoctor
before_install:
- gem install asciidoctor
before_script:
- "./.travis/setup-kubernetes.sh"
script:
- "./.travis/build.sh"
env:
  global:
  - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - COMMIT=${TRAVIS_COMMIT::8}
  - TAG=${TRAVIS_TAG:-latest}
  - BRANCH=${TRAVIS_BRANCH:-master}
  - DOCKER_ORG=strimzici
  - TEST_CLUSTER=minikube
  - TEST_KUBECTL_VERSION=v1.10.0
  - TEST_MINIKUBE_VERSION=v0.25.2
  - secure: 3OzqWb5bpFBS9Wdm2H+alyo2P6ghjNRFeRdfIKw8HF6o0jBhZBamP3WpGH/HzKuF//Sizu0+DnI4iYrNmQRu/+yI0Yz6MaBJdtJT0GkD8GrIdnaYzWkFVTo+o/QPhnCaqHwbFgTipNeMxDaJ9ErhZWR/nrrSNLRjZi8hVm3Ckuq9DW/tsmhU4IAMDAeAjkk+MFvnKiFcIuryE5EQqcGM51VlSsCoMn1qT8R0wVMMggKY7qO+oK2Rxrmpauo+oh5i3evbxCUBguMhjJJTTQ5HAmJg6ZpCisJZnYDmF4c1Ei5OqMINdHWj2z0itltTdF6Chrxp3+fRsWf9Sp+f//g446SPOO2Xil8igK+LaHF0FGwHzIcw9U1NLGZjFoka028T0dNUfsHN6w3X8fVNFop2GAAkfbtuVfy6QZvTBD8ZwNErAge/dvhMh1cooGNsUm3U5BWXdBj5mFkZsQ6FYJCVqMC8FxLnc8LTYzkR1/qhRWiuwmE2spvV5eLOpUZfgY/xJ6rgc/s83bq+HyhoqHCNZWNf8Z/QwqRIzziHD2gkZqPnC6suW8BSJM7Nk2iHxtKv1lIS0wDPBnUHiIgssFi803HMmsQr8hj80ETjis4ewTOBPJosTcY5GP5jFSAqbcDtF4intSDPxJ6fylWPzMWCVARzYb7g3remvD7ec7aa8so=
  - secure: 5OwpooVBd2fbfDwN4QmRqvVQLLuk5VET4ZON7GtF04eDEgFFAsygb+3PN4AKuVE0/hNkK0gUZLPBPojtwaxd0gA47bsDL4QX8a+6jmu+8bv+GzM0Qtw0SrkbP7Zxt8qCQ3cH0GvK6oQbzF9KWnA0dYuc/2sDJW2YzNmwW3QuMJuBbPL7GmmiOC1eeuU9CkM04s8zSV6kFFqqmcgEol4pN2otszsglfGZhxdjnT75iAEjonUicXNO7ew3aEhVPHeYYSmM/hyY1fjmwHXFCRHhPVCg5bklxRFwO8EqlQMNJp97Cn69Jo97RdM487n74gfXeft/2gOWkxvJnp1ufFtvVtuGoj8d/N93eQRmm4bs5h4BFaXKv98IoTQEb1nAc4zqysssu3UIWQ2TQGGGBuBYpEWF3ms5nPINWi0cpGDB/TWC0hEoThYFqOhuQU6kpZJRU9mWk1SnRDqTulhXSNPGnHiu4HGKZhPYtWR3QvVa81IlwKp7UkWxJPSbnxcii4lKwurDoXeX1+V4z9lrROCgyzuqmzIPU+Z6t80A7xwu/F/803SiAxMxrEgDdG3QhKlElMGKHJwu+vZKWU29t+nHTbveXB0cWf4kqa9lv16yu0/L6xMSupwC62TCtN4/KVZuSA4vmYine9BhWHIcwmu8dIZVOR7pNJERymPT1GOTPn4=
